let res = [
    `T&#8217;eqt&#8217;aqtn&#8217;mux`,
    `K&#8217;ómoks`,
    `kʷikʷəƛ̓əm`,
    `nuučaan̓uuɫɁatḥ nism̓a (Nuu-chah-nulth)`,
    `Hesquiaht`,
    `S’ólh Téméxw (Stó:lō)`,
    `ditidaqiic̓aq disib̓aʔk (Ditidaht)`,
    `Tse’khene`,
    `Semiahmoo`,
    `S&#8217;Klallam`,
    `Dakeł Keyoh (ᑕᗸᒡ ᗲᘏᑋ)`,
    `Qayqayt`,
    `Lil&#8217;wat`,
    `Ktunaxa ɁamakɁis`,
    `Sturgeon Lake Cree`,
    `Gwa&#8217;Sala-&#8216;Nakwaxda&#8217;xw`,
    `Duwamish`,
    `Big Stone Cree`,
    `Á,LEṈENEȻ ȽTE (W̱SÁNEĆ)`,
    `Wuikinuxv (Oweekeno)`,
    `Dene Tha&#8217;`,
    `In-SHUCK-ch`,
    `Yekooche`,
    `Pacheedaht`,
    `snʕickstx tmxʷúlaʔxʷ (Sinixt)`,
    `Kelly Lake Metis Settlement Society`,
    `Lekwungen/Songhees`,
    `np̓əšqʷáw̓səxʷ (Wenatchi)`,
    `As&#8217;in&#8217;i&#8217;wa&#8217;chi Niy&#8217;yaw Askiy (Rocky Mountain Cree)`,
    `Hul&#8217;qumi&#8217;num Treaty Group`,
    `Woodland Cree`,
    `Kalispel`,
    `shíshálh swíya (Sechelt)`,
    `Hupacasath`,
    `Kulhulmcilh (Nuxalk)`,
    `Nłeʔkepmx Tmíxʷ (Nlaka&#8217;pamux)`,
    `Kwantlen`,
    `Skagit`,
    `səl̓ilwətaɁɬ təməxʷ (Tsleil-Waututh)`,
    `Tŝilhqot’in Nen`,
    `Wet&#8217;suwet&#8217;en Yintikh`,
    `ɬaʔamɩn gɩǰɛ (Tla’amin)`,
    `Schitsu&#8217;umsh (Coeur d&#8217;Alene)`,
    `sc̓əwaθenaɁɬ təməxʷ (Tsawwassen)`,
    `Suquamish`,
    `Salish &#038; Kootenai Tribes`,
    `Beaver`,
    `Da&#8217;naxda&#8217;xw Awaetlatla`,
    `Quatsino`,
    `Quileute`,
    `Secwepemcúl’ecw (Secwépemc)`,
    `Lhaq’temish (Lummi)`,
    `Homalco`,
    `sq̓əc̓iy̓aɁɬ təməxʷ (Katzie)`,
    `Tsuut&#8217;ina`,
    `Twana/Skokomish`,
    `ƛohos giǰi (Klahoose)`,
    `šxʷməθkʷəy̓əmaɁɬ təməxʷ (Musqueam)`,
    `ChalAt’i’lo t’sikAti (Chalat’)`,
    `Qʷidiččaʔa•tx̌ (Makah)`,
    `Kwakwaka&#8217;wakw A̱wi&#8217;nagwis`,
    `Syilx (Okanagan)`,
    `Te&#8217;mexw Treaty Association`,
    `Denendeh (Acho Dene Koe)`,
    `Skwxwú7mesh-ulh Temíx̱w (Squamish)`,
    `St̓át̓imc Tmicw (St&#8217;at&#8217;imc)`,
    `Snohomish`,
    `Tseshaht`,
    `sdukʷalbixʷ (Snoqualmie)`,
    `Nuxwsa&#8217;7aq (Nooksack)`,
    `Samish`,
    `Nuwhaha`,
    `sp̓aƛ̓mul̓əxʷəxʷ (Methow)`,
    `ščəl’ámxəxʷ (Chelan)`,
    `šntiyátkʷəxʷ (Entiat)`,
    `nspiləm (Nespelem)`,
    `sńpʕawílx (Sanpoil)`,
    `sx̌ʷyʔiɬp (Colville)`,
    `Swinomish`,
    `Stz&#8217;uminus`,
    `Chimacum`,
    `Huu-ay-aht`,
    `Musgamagw Dzawada&#8217;enuxw`,
    `Tulalip`,
    `Lheidli T&#8217;enneh`,
    `Toquaht`,
    `Uchucklesaht`,
    `Yuułuʔiłʔatḥ`,
    `Ka:’yu:’k’t’h’/Che:k’tles7et’h’`,
    `We Wai Kai`,
    `We Wai Kum`,
    `Skykomish`,
    `Stillaguamish`,
    `Takla`,
    `ƛaʔuukʷiʔatḥ (Tla-o-qui-aht)`,
    `Esketemculeucw (Esk&#8217;etemc)`,
    `Nadleh Whut&#8217;en`,
    `Stellat&#8217;en`,
    `Dënéndeh`,
    `Queets`,
    `BOḰEĆEN (Pauquachin)`,
    `W̱SĺḴEM (Tseycum)`,
    `W̱JOȽEȽP (Tsartlip)`,
    `MÁLEXEȽ (Malahat)`,
    `Sauk Suiattle`,
    `Mountain Métis`,
    `Quw&#8217;utsun`,
    `Halalt`,
    `Ts’uubaa-asatx`,
    `KiKiallus`,
    `Snaw-naw-as`,
    `Confederated Tribes of the Colville Reservation`,
    `Liǧʷiłdax̌ʷ`,
    `Kwiakah`,
    `Sc&#8217;ianew`,
    `Nadut&#8217;en`,
    `Nadut&#8217;en`,
    `Nadu&#8/217;en`
]

// TODO: two versions, one leaves the space where it is (for the title), 
// TODO: other replaces it with underscore, for the URL

function sanitizeStringForURL(str){
    let sanitized = str.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '')
    sanitized = sanitized.replace(/\s/g, '_')
    return sanitized
}



// loop through the array of strings, use regex method below, print result, 
for(let s of res){
    let sani = sanitizeStringForURL(s)
    console.log(sani)
}

// var outString = sourceString.
// replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '');

// console.log(outString);


