import Head from 'next/head'
import styled from 'styled-components'

import Map from '../components/Map'
import { SearchGroup } from '../components/Search/SearchGroup'
import { Navbar } from '../components/Navbar/Navbar'

// enter styled components
const StyledMain = styled.main`
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
`

export default function Home() {

  const filterToggles = [
    { key: 1, label: "Arts", selected: true },
    { key: 2, label: "Tourism", selected: false },
    { key: 3, label: "Language", selected: false },
  ]


  return (
    <div>
      <Head>
        <title>First Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/location-dot-solid.svg" />
      </Head>

      <StyledMain>
        <Map />
        <SearchGroup activeFilter={true} filterToggles={filterToggles} />
        <Navbar />
      </StyledMain>
      
    </div>
  )
}
