import Head from 'next/head'
import styled from 'styled-components'

import Map from '../components/Map'
import { Search } from '../components/Search/Search'

// enter styled components
const StyledMain = styled.main`
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
`

export default function Home() {

  return (
    <div>
      <Head>
        <title>First Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/location-dot-solid.svg" />
      </Head>

      <StyledMain>
        <Map />
        <Search />
      </StyledMain>
      
    </div>
  )
}
